FORMAT: 1A
HOST: http://polls.apiblueprint.org/v3/

# emptor-dev

Two different endpoints.

## Persons [/persons]

### List All People [GET]

This action returns a 200 status code along with a JSON body.

## Reports [/reports]

### List All Reports [GET]

This action returns a 200 status code along with a JSON body.